### ISSUE TITLE
More randomization of rand()

### ISSUE THREAD

**Issue by Arka-h** [Arka-h/KBC#2]
### **PRIMARY PROBLEM**

- The rand() allows repetition when used multiple times.

- **We need to modify it to give unique outputs**

+

### **SECONDARY PROBLEM**

- If you run the KBC.c as it is right now,
you'd find that the same questions get chosen quite a lot of times.

- This is mainly due to questions been chosen at regular intervals of time[the basis of rand()]

- **Randomize the rand() function even more.
Use if else to switch between different hybrid versions of rand() or something.**

**Comment by Jainamjain123** [comment]
#include<stdio.h>
int main()
{
int E[45];
int i;
int a=0;
for(i=0;i<45;i++)
{
if(E[i]!=a)
{
E[i]=rand()%45;
printf("%d\n",E[i]+1);
}
else
{a=E[i];}
}}

**Comment by Arka-h** [comment]
```#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>
#include<time.h>

int main()
{  
     srand(time(0));
     int i=0,temp1,temp2;
	short int E[5];
	char a[45];
	while ( i<45)
	a[i++]=0;
	i=0;
	while ( i <5)
	{
		E[i]=rand()%30;
		temp1=E[i];
		if(a[E[i]]==0)
		{
			temp2=E[i];
			a[E[i++]]=1;
		}
		printf("*%d*--assigned value",temp1);
		printf("\n");
		printf("%d  --carried value",temp2);
		printf("\n\n");
	}
	printf("FINAL VALUES:\n");
	for(int j=0;j<5;j++)
	printf("%d ",E[j]);
	return 0;	
}```

**Comment by Arka-h** [comment]
```#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>
#include<time.h>

int main()
{  
     srand(time(0));
     
	short int E[5];
	char a[45];
	
	while ( i<45)
	a[i++]=0;
	
	i=0;
	while ( i <5)
	{
		E[i]=rand()%30;
		
		if(a[E[i]]==0)
			a[E[i++]]=1;
	}
	printf("FINAL VALUES:\n");
	for(int j=0;j<5;j++)
	printf("%d ",E[j]);
	return 0;	
}```
